from Orientation import Orientation
from telegram.ext import ConversationHandler


TOKEN = "1031385889:AAEGzeUIUG_35rPSHA8-GMH8WzWnxmWuzx0"

PORTRAIT = str(Orientation.portrait)
LANDSCAPE = str(Orientation.landscape)
SELECTING_ORIENTATION = "SELECTING_ORIENTATION"
ORIENTATION = "ORIENTATION"
END = ConversationHandler.END
SETTINGS = "SETTINGS"
SETTING_SCALE = "SETTING_SCALE"
SETTING_COPIES = "SETTING_COPIES"
COPIES = "COPIES"
SCALE = "SCALE"
PRINT = "PRINT"
CHOOSE_SETTING = "CHOOSE_SETTING"
PRINTING = "PRINTING"
